name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install tools
      working-directory: ${{github.workspace}}
      run: |
        sudo apt-get update
        sudo apt-get -y install git cmake gcc g++ xxd libssl-dev libgtest-dev libcurl4-openssl-dev openssh-server ufw sshpass curl jq

    - name: Install OpenSSL
      working-directory: ${{github.workspace}}
      run: |
        git clone git://git.openssl.org/openssl.git
        cd openssl
        git checkout openssl-3.1.4
        ./config
        make
        sudo make install
        sudo ln -sf /usr/local/lib64/libssl.so.3 /usr/local/lib/libssl.so
        sudo ln -sf /usr/local/lib64/libcrypto.so.3 /usr/local/lib/libcrypto.so
        sudo ln -sf /usr/local/lib64/libssl.so.3 /usr/lib/x86_64-linux-gnu/libssl.so
        sudo ln -sf /usr/local/lib64/libcrypto.so.3 /usr/lib/x86_64-linux-gnu/libcrypto.so
        sudo echo "/usr/local/lib64" >> /etc/ld.so.conf
        ldconfig
        cd ..
        rm -rf openssl
        openssl version

    - name: Download SDK
      working-directory: ${{github.workspace}}
      run: |
        sdk_file='qrypt-security-ubuntu.tgz'
        curl -s https://qrypt.azureedge.net/sdk/cpp/v0.11.14/qrypt-security-0.11.14-ubuntu.tgz --output $sdk_file
        tar -zxvf $sdk_file --strip-components=1 -C QryptSecurity
        rm -rf $sdk_file
    
    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_TESTS=ON

    - name: Build
      working-directory: ${{github.workspace}}
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Validation Tests
      working-directory: ${{github.workspace}}
      run: ./qrypt test
    
    - name: CLI Test
      working-directory: ${{github.workspace}}
      run: ./qrypt generate --key-filename=alice.dat && ./qrypt replicate --key-filename=bob.dat && cmp alice.dat bob.dat || { echo "Alice and Bob key files do not match"; exit 1; }
